import type { Metadata } from 'next'
import '@/assets/styles/index.scss'
import cx from 'clsx'
import Fonts from '@/assets/fonts'
import Providers from '@/components/layout/providers'
import { Toaster } from '@/components/ui/sonner'

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cx(Fonts.galins.variable, Fonts.sofia.variable)}>
        <Providers>
          {children}
          <Toaster richColors duration={1000} position="bottom-left" />
        </Providers>
      </body>
    </html>
  )
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
